export const API_CATALOG = [
  {
    group: "admin",
    method: "POST",
    path: "/api/admin/login",
    title: "Admin login",
    auth: "public",
    body: `{ "email": "admin@helpline.org", "password": "admin123" }`,
    notes: "Sets httpOnly admin_token cookie.",
    sortOrder: 1,
  },
  {
    group: "admin",
    method: "POST",
    path: "/api/admin/logout",
    title: "Admin logout",
    auth: "admin cookie",
    notes: "Clears admin_token cookie.",
    sortOrder: 2,
  },
  {
    group: "admin",
    method: "GET",
    path: "/api/admin/me",
    title: "Current admin",
    auth: "admin cookie",
    sortOrder: 3,
  },
  {
    group: "admin",
    method: "POST",
    path: "/api/admin/password",
    title: "Change admin password",
    auth: "admin cookie",
    body: `{ "currentPassword": "admin123", "newPassword": "new-password" }`,
    notes: "Requires the current password. New password must be at least 6 characters.",
    sortOrder: 3,
  },
  {
    group: "admin",
    method: "GET",
    path: "/api/admin/stats",
    title: "Dashboard stats",
    auth: "admin cookie",
    notes: "Today’s check-ins, reports, projects by type.",
    sortOrder: 4,
  },
  {
    group: "admin",
    method: "GET",
    path: "/api/admin/project-types",
    title: "List project types",
    auth: "admin cookie",
    sortOrder: 5,
  },
  {
    group: "admin",
    method: "POST",
    path: "/api/admin/project-types",
    title: "Create project type",
    auth: "admin cookie",
    body: `{ "name": "Water Project", "color": "sky" }`,
    sortOrder: 6,
  },
  {
    group: "admin",
    method: "PATCH",
    path: "/api/admin/project-types/:id",
    title: "Update project type",
    auth: "admin cookie",
    body: `{ "name": "Clean Water", "color": "teal" }`,
    sortOrder: 7,
  },
  {
    group: "admin",
    method: "DELETE",
    path: "/api/admin/project-types/:id",
    title: "Delete project type",
    auth: "admin cookie",
    notes: "Blocked if any project still uses this type.",
    sortOrder: 8,
  },
  {
    group: "admin",
    method: "GET",
    path: "/api/admin/projects",
    title: "List projects",
    auth: "admin cookie",
    notes: "Query: ?q=&type=&status=",
    sortOrder: 9,
  },
  {
    group: "admin",
    method: "POST",
    path: "/api/admin/projects",
    title: "Create project",
    auth: "admin cookie",
    body: `{ "name": "Al-Kitab School", "code": "SCH-001", "type": "SCHOOL", "location": "Rajanpur" }`,
    sortOrder: 10,
  },
  {
    group: "admin",
    method: "GET",
    path: "/api/admin/projects/:id",
    title: "Get project",
    auth: "admin cookie",
    sortOrder: 11,
  },
  {
    group: "admin",
    method: "PATCH",
    path: "/api/admin/projects/:id",
    title: "Update project",
    auth: "admin cookie",
    sortOrder: 12,
  },
  {
    group: "admin",
    method: "PUT",
    path: "/api/admin/projects/:id",
    title: "Replace project",
    auth: "admin cookie",
    notes: "Same as PATCH.",
    sortOrder: 13,
  },
  {
    group: "admin",
    method: "DELETE",
    path: "/api/admin/projects/:id",
    title: "Delete project",
    auth: "admin cookie",
    sortOrder: 14,
  },
  {
    group: "admin",
    method: "POST",
    path: "/api/admin/projects/:id/assign",
    title: "Assign employees to project",
    auth: "admin cookie",
    body: `{ "employeeIds": ["employee-id"] }`,
    sortOrder: 15,
  },
  {
    group: "admin",
    method: "DELETE",
    path: "/api/admin/projects/:id/assign",
    title: "Unassign employee from project",
    auth: "admin cookie",
    body: `{ "employeeId": "employee-id" }`,
    sortOrder: 16,
  },
  {
    group: "admin",
    method: "GET",
    path: "/api/admin/employees",
    title: "List employees",
    auth: "admin cookie",
    notes: "Query: ?q=&status=&role=&projectId=",
    sortOrder: 17,
  },
  {
    group: "admin",
    method: "POST",
    path: "/api/admin/employees",
    title: "Create employee",
    auth: "admin cookie",
    body: `{ "name": "Muhammad Ahmed", "email": "ahmed@helpline.org", "phone": "03001234501", "designation": "Teacher", "role": "STAFF", "password": "Emp@123" }`,
    sortOrder: 18,
  },
  {
    group: "admin",
    method: "GET",
    path: "/api/admin/employees/:id",
    title: "Get employee",
    auth: "admin cookie",
    sortOrder: 19,
  },
  {
    group: "admin",
    method: "PATCH",
    path: "/api/admin/employees/:id",
    title: "Update employee",
    auth: "admin cookie",
    notes: "Fields: name, email, phone, designation, role (STAFF|SUPERVISOR), status, password.",
    sortOrder: 20,
  },
  {
    group: "admin",
    method: "DELETE",
    path: "/api/admin/employees/:id",
    title: "Delete employee",
    auth: "admin cookie",
    sortOrder: 21,
  },
  {
    group: "admin",
    method: "POST",
    path: "/api/admin/employees/:id/assign",
    title: "Assign projects to employee",
    auth: "admin cookie",
    body: `{ "projectIds": ["project-id"] }`,
    sortOrder: 22,
  },
  {
    group: "admin",
    method: "DELETE",
    path: "/api/admin/employees/:id/assign",
    title: "Unassign project from employee",
    auth: "admin cookie",
    body: `{ "projectId": "project-id" }`,
    sortOrder: 23,
  },
  {
    group: "admin",
    method: "GET",
    path: "/api/admin/attendance",
    title: "Attendance for a day",
    auth: "admin cookie",
    notes: "Query: ?date=YYYY-MM-DD&projectId=",
    sortOrder: 24,
  },
  {
    group: "admin",
    method: "GET",
    path: "/api/admin/reports",
    title: "List daily reports",
    auth: "admin cookie",
    notes: "Query: ?q=&projectId=&employeeId=&date=",
    sortOrder: 25,
  },
  {
    group: "admin",
    method: "GET",
    path: "/api/admin/notifications",
    title: "Admin report notifications",
    auth: "admin cookie",
    notes: "Unread count plus recent report alerts for the dashboard bell.",
    sortOrder: 26,
  },
  {
    group: "admin",
    method: "POST",
    path: "/api/admin/notifications",
    title: "Mark all notifications read",
    auth: "admin cookie",
    body: `{ "action": "read-all" }`,
    sortOrder: 27,
  },
  {
    group: "admin",
    method: "PATCH",
    path: "/api/admin/notifications/:id",
    title: "Mark one notification read",
    auth: "admin cookie",
    sortOrder: 28,
  },
  {
    group: "admin",
    method: "GET",
    path: "/api/admin/reports/:id",
    title: "Report detail",
    auth: "admin cookie",
    sortOrder: 29,
  },
  {
    group: "admin",
    method: "GET",
    path: "/api/admin/apis",
    title: "API catalog stored in MongoDB",
    auth: "admin cookie",
    sortOrder: 30,
  },
  {
    group: "app",
    method: "POST",
    path: "/api/app/login",
    title: "Employee login",
    auth: "public",
    body: `{ "email": "ahmed@helpline.org", "password": "Emp@123" }`,
    notes: "Returns JWT with appRole STAFF or SUPERVISOR. Send as Authorization: Bearer <token>.",
    sortOrder: 1,
  },
  {
    group: "app",
    method: "GET",
    path: "/api/app/me",
    title: "Current employee + today status",
    auth: "employee bearer",
    notes: "Assigned projects, check-in/out, today’s reports.",
    sortOrder: 2,
  },
  {
    group: "app",
    method: "GET",
    path: "/api/app/types",
    title: "Project types",
    auth: "employee bearer",
    sortOrder: 3,
  },
  {
    group: "app",
    method: "GET",
    path: "/api/app/projects",
    title: "Assigned projects",
    auth: "employee bearer",
    sortOrder: 4,
  },
  {
    group: "app",
    method: "POST",
    path: "/api/app/checkin",
    title: "Daily check-in",
    auth: "employee bearer",
    body: `{ "projectId": "optional-project-id" }`,
    notes: "One check-in per employee per day.",
    sortOrder: 5,
  },
  {
    group: "app",
    method: "POST",
    path: "/api/app/reports",
    title: "Submit daily report",
    auth: "employee bearer",
    body: `{ "projectId": "required-project-id", "summary": "Short summary", "details": "Full report" }`,
    notes: "Staff can submit more than one report per day. Check-out is a separate action.",
    sortOrder: 6,
  },
  {
    group: "app",
    method: "POST",
    path: "/api/app/checkout",
    title: "Check-out only",
    auth: "employee bearer",
    sortOrder: 7,
  },
  {
    group: "app",
    method: "GET",
    path: "/api/app/reports",
    title: "Own reports history",
    auth: "employee bearer",
    sortOrder: 8,
  },
  {
    group: "app",
    method: "GET",
    path: "/api/app/attendance",
    title: "Own attendance history",
    auth: "employee bearer",
    notes: "Query: ?from=2026-09-01&to=2026-09-14",
    sortOrder: 9,
  },
  {
    group: "app",
    method: "GET",
    path: "/api/app/team",
    title: "Supervisor team for today",
    auth: "supervisor bearer",
    notes: "Staff on the same assigned projects. Attendance and reports for today (Pakistan date).",
    sortOrder: 10,
  },
] as const;
